name: Discord Notifications

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, closed]
  release:
    types: [published]

jobs:
  notify-discord
    runs-on: ubuntu-latest
    steps:
      - name: Forward event to Discord Native Webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          WEBHOOK_URL=${{DISCORD_WEBHOOK%/}/github"

          curl -s -S -X POST \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: ${{ github.event_name }}" \
            -d @$GITHUB_EVENT_PATH \
            "$WEBHOOK_URL"